### ISSUE TITLE
error

### ISSUE THREAD

**Issue by goldentg** [Vedzaa/NitroSniperGo#6] opened 2020-07-14 21:38 UTC
when launched, it gives this error then doesn't do anything when nitro codes or giveaways are sent 

![image](https://user-images.githubusercontent.com/43283685/87479055-04183000-c5e8-11ea-9590-96a2d47e8358.png)

**Comment by Vedzaa** [comment] 2020-07-30 05:56
Are you sure it doesn't do anything when nitro codes or giveaways are sent? 
This error comes from discordgo library but it seems that everything works fine for most people when they get this error.

**Comment by goldentg** [comment] 2020-07-30 15:52
nope. sends the second it starts and doesnt gather potential giveaway codes after. at least with my experiance

**Comment by Gnavling** [comment] 2020-08-14 21:26
I have the same issue

**Comment by SloppyPuppy** [comment] 2020-09-16 21:01
same issue here, have yet to see if it actually works with codes, but the python version reported claimed codes yet it didn't seem to work, so it is a possibility with something on my end.

**Comment by Vedzaa** [comment] 2020-09-16 21:11
I think you're talking about a different issue than the one on this issue but I add a case "cannot check validity". Sometimes it happens when the gift is a game (check in library), sometimes it just doesn't work, even on discord app.

**Comment by SloppyPuppy** [comment] 2020-09-16 22:52
Well it's printing the same thing ([DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_message_id of type string), but right now I am just unsure if It hasn't snipped any codes yet or if the program is just not working for me.

**Comment by SloppyPuppy** [comment] 2020-09-16 22:53
Btw really appreciate your work and the fact that you interact with community 👍

**Comment by Vedzaa** [comment] 2020-09-17 08:03
No problem ! You can test it by sending a gift link in any channel (here is one if you need discord.com/gifts/duHW5XPgE8AYsvWD2qCZ4EcH). If it prints something then it's working

**Comment by Vedzaa** [comment] 2020-09-17 08:15
Btw I'm sorry for anyone who has this unmarshalling error but I can't find out as the error comes from a dependence and I can't reproduce it myself to debug it. Someone told me that he didn't get the error after removing the "Discord Sniper" print, it would be nice if someone here can test that and tell me if it works.

**Comment by PeterStrick** [comment] 2020-09-17 09:00
> Btw I'm sorry for anyone who has this unmarshalling error but I can't find out as the error comes from a dependence and I can't reproduce it myself to debug it. Someone told me that he didn't get the error after removing the "Discord Sniper" print, it would be nice if someone here can test that and tell me if it works.

I tested it by making two builds.

Build 1: Replace the Discord Nitro Sniper print with test
Build 2: Removed the Sniper print entrely

The error still exists in both builds.

**Comment by Vedzaa** [comment] 2020-09-17 09:03
Ok thanks, that's what I thought. It would have been really weird if it was the solution

**Comment by PeterStrick** [comment] 2020-09-17 09:04
After some examination of sniper.go, Visual Studio Code gives a warning on the token variable.

![image](https://user-images.githubusercontent.com/60312421/93449702-5a01a080-f8d5-11ea-95e4-899ab3dbc3e3.png)

**Comment by PeterStrick** [comment] 2020-09-17 09:10
Found an issue on the discordgo repo with the same problem
https://github.com/bwmarrin/discordgo/issues/773

Seems like the error message is normal?

**Comment by Vedzaa** [comment] 2020-09-17 09:28
Yeah I saw that but it seems like it make the bot doesn't work for some people

> This error comes from discordgo library but it seems that everything works fine for most people when they get this error.

> nope. sends the second it starts and doesnt gather potential giveaway codes after. at least with my experiance

But maybe they just didn't understand that it was working because they didn't get 10 months of nitro in 10 sec. If nobody can't prove me that it doesn't snipe nitro with this error I'll just close the issue then

**Comment by SloppyPuppy** [comment] 2020-09-17 20:56
I think the bot works fine, it's just for some reason slow for me because i've been running the program for about 24 hours now and I have yet to have a successful snipe, its always either claimed or sometimes it says it claimed it himself but it doesn't claim it. I've checked the gifts section with no luck. Do you have any tips on how to optimize the snipe time? (running the bot on 83 servers)

**Comment by Vedzaa** [comment] 2020-09-17 21:07
You just have to wait. I run it on my vps and sometimes it takes a day, sometimes a week. The only thing I can recommend is to stop it a few days or weeks when you get 4/5 months, and join all kind of server with more or less people in it. 
Did you get `[+] Code applied` ?
You should have this only if you got Nitro.

**Comment by SloppyPuppy** [comment] 2020-09-17 21:09
Yes I got the [+] Code applied twice but it didn't actually apply.

**Comment by Vedzaa** [comment] 2020-09-17 21:10
Can you give me your discord pls ?

**Comment by SloppyPuppy** [comment] 2020-09-17 21:10
And I've joined quite a network of servers with 10s of thousands of people and plan to join more.

**Comment by SloppyPuppy** [comment] 2020-09-17 21:10
龍癌#5273 here ya go

**Comment by SloppyPuppy** [comment] 2020-09-17 21:10
didn't know github posts update real time xD

**Closed** 2020-09-17 21:42 UTC
